version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medoptix-api
    ports:
      - "8000:8000"
    env_file:
      - aws.env
      - aiven.env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./models:/app/models
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: postgres:16
    container_name: medoptix-db
    environment:
      POSTGRES_USER: medoptix
      POSTGRES_PASSWORD: medoptix_password
      POSTGRES_DB: medoptix_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db_data:
